# -*- coding: utf-8 -*-
"""Flask Food Warning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dy0m9xhJmlOsmHIN5OtvntIUHAJ5GdXh
"""

from flask import Flask, request, send_file
import matplotlib.pyplot as plt
import numpy as np
import io

app = Flask(__name__)

@app.route('/generate_plot', methods=['POST'])
def generate_plot():
    # Ambil data dari permintaan POST
    data = request.get_json()
    # Proses data (misalnya, hitung plot berdasarkan data)
    x = np.arange(len(data))
    # Create the plot
    fig, ax = plt.subplots()

    # Plot the calories data
    ax.plot(x, calories, label='Calories', color='teal', linewidth=3)

    # Highlight points exceeding the target
    exceeding_points = np.where(np.array(calories) > target)[0]
    ax.plot(exceeding_points, np.array(calories)[exceeding_points], 'ro', label='Exceeds Target')

    # Plot the target line
    ax.axhline(y=target, color='red', linestyle='--', linewidth=2, label='Target: 800 kcal')

    # Customize the plot
    ax.set_xticks(x)
    ax.set_xticklabels(dates)
    ax.set_yticks(np.arange(0, 1400, 200))
    ax.set_yticklabels(['0', '200', '400', '600', '800', '1000', '1200'])
    ax.set_ylim(0, 1400)

    # Add labels and title
    plt.title('Your Calories')
    ax.text(0, 1300, 'Targets: 800 kcal', ha='left', fontsize=12)
    plt.ylabel('Calories')

    # Display warning text
    if len(exceeding_points) > 0:
        ax.text(0, 1100, 'Warning: Melebihi Target!', color='red', fontsize=10)
    # Add legend
    plt.legend()
    # Simpan plot sebagai file gambar sementara
    img_buffer = io.BytesIO()
    plt.savefig(img_buffer, format='png')
    img_buffer.seek(0)
    # Kirim file gambar plot sebagai respons
    return send_file(img_buffer, mimetype='image/png')

if __name__ == '__main__':
    app.run(debug=True)