# -*- coding: utf-8 -*-
"""food warning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geM1Y3mxvQcJNpb-ELlZnIcXeQwLGRhd
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample data
dates = ['May 14', 'May 15', 'May 16', 'May 17', 'May 18', 'May 19', 'May 20']
calories = [500, 600, 900, 1200, 900, 600, 400]
target = 800

# Convert dates to numeric format for plotting
x = np.arange(len(dates))

# Create the plot
fig, ax = plt.subplots()

# Plot the calories data
ax.plot(x, calories, label='Calories', color='teal', linewidth=3)

# Highlight points exceeding the target
exceeding_points = np.where(np.array(calories) > target)[0]
ax.plot(exceeding_points, np.array(calories)[exceeding_points], 'ro', label='Exceeds Target')

# Plot the target line
ax.axhline(y=target, color='red', linestyle='--', linewidth=2, label='Target: 800 kcal')

# Customize the plot
ax.set_xticks(x)
ax.set_xticklabels(dates)
ax.set_yticks(np.arange(0, 1400, 200))
ax.set_yticklabels(['0', '200', '400', '600', '800', '1000', '1200'])
ax.set_ylim(0, 1400)

# Add labels and title
plt.title('Your Calories')
ax.text(0, 1300, 'Targets: 800 kcal', ha='left', fontsize=12)
plt.ylabel('Calories')

# Display warning text
if len(exceeding_points) > 0:
    ax.text(0, 1100, 'Warning: Melebihi Target!', color='red', fontsize=10)

# Add legend
plt.legend()

# Display the plot
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Meminta pengguna memasukkan data kalori harian
calories = []
for i in range(7):
    daily_calories = int(input(f"Masukkan jumlah kalori untuk {dates[i]}: "))
    calories.append(daily_calories)

# Meminta pengguna memasukkan target kalori
target = int(input("Masukkan target kalori harian Anda: "))

# Convert dates to numeric format for plotting
x = np.arange(len(dates))

# Create the plot
fig, ax = plt.subplots()

# Plot the calories data
ax.plot(x, calories, label='Calories', color='teal', linewidth=3)

# Highlight points exceeding the target
exceeding_points = np.where(np.array(calories) > target)[0]
ax.plot(exceeding_points, np.array(calories)[exceeding_points], 'ro', label='Exceeds Target')

# Plot the target line
ax.axhline(y=target, color='red', linestyle='--', linewidth=2, label='Target: {} kcal'.format(target))

# Customize the plot
ax.set_xticks(x)
ax.set_xticklabels(dates)
ax.set_yticks(np.arange(0, max(calories) + 200, 200))  # Menggunakan nilai maksimal kalori harian untuk menentukan range y-ticks
ax.set_yticklabels([str(i) for i in np.arange(0, max(calories) + 200, 200)])
ax.set_ylim(0, max(calories) + 200)  # Menambahkan margin atas 200 kalori untuk plot

# Add labels and title
plt.title('Your Calories')
ax.text(0, max(calories) + 150, 'Targets: {} kcal'.format(target), ha='left', fontsize=12)
plt.ylabel('Calories')

# Display warning text
if len(exceeding_points) > 0:
    ax.text(0, max(calories) + 100, 'Warning: Melebihi Target!', color='red', fontsize=10)

# Add legend
plt.legend()

# Display the plot
plt.show()