# -*- coding: utf-8 -*-
"""drink quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Nz2BaHKJbdmGG0uQKLrRuW24YODeS_q
"""

def drink_quality_percentage(num_glasses):
    max_glasses = 8  # Jumlah gelas maksimum per hari
    if num_glasses >= max_glasses:
        return 100
    else:
        return (num_glasses / max_glasses) * 100

# Contoh
num_glasses_today = 6

drink_quality_today = drink_quality_percentage(num_glasses_today)
print(f"Kualitas minum hari ini: {drink_quality_today}%")